<div class="table table-responsive" style="width: 330px; margin: 50px 0 0 450px; border:0.5px solid #003cb3; padding: 15px">
    <form method="post" action="/magicPhalcon/sign/in" name="login">
        <div class="form-group" style="width: 300px;">
            <label for="login_email">Login:</label>
            <input type="text" name="login_email" id="login_email" 
                class="form-control" required placeholder='Digite seu login ou e-mail'
            />
            <label for="password">Senha:</label>
            <input type="password" name="password" id="password"
                class="form-control" required placeholder='Digite sua senha de 6 a 12 digitos'
            />
            <br>
            <input type="reset" value="Limpar" class="label alert">
            <div style="float:right;">
            <button type="submit" class="btn alert">Entrar em Tarkir</button>
            </div>
        </div>
    </form>
<hr>
	<span>Nao é cadastrado ainda?
        <a href="/magicPhalcon/sign/up" class="label alert">Crie sua conta agora!</a>
    </span>
    <br>
</div>