<br><br>
<?php

?>
<br>
<div class="row" data-equalizer style="float: left; margin-left: 100px;">
    <div class="small-10 large-5 columns panel left" data-equalizer-watch>
        <h3><small>Ver Coleção</small></h3>
        <form action="cards/" method="post">
            <select class="form-control" name="col">
                <option value='0'>Select a Collection</option>
                <?php foreach($allCollections as $collection):
                    echo "<option value='$collection[id]'> $collection[name] </option>";
                endforeach; ?>
            </select>
            <h3><small>Filter By:</small></h3>
            <div class="panel">
                <label>Mana Cost</label>
                <select class="form-control" name="mana">
                    <option value=0>Select option</option>
                    <option value=1>1 Mana Cost</option>
                    <option value=2>2 Mana Cost</option>
                    <option value=3>3 Mana Cost</option>
                    <option value=4>4 Mana Cost</option>
                    <option value=5>5 Mana Cost</option>
                    <option value=6>6 Mana Cost</option>
                    <option value=7>7 Mana Cost</option>
                    <option value=8>8 Mana Cost</option>
                </select>

                <label>Cor: </label>
                <select class="form-control" name="color">
                    <option value=0>Select option</option>
                    <option value=Blue>Azul</option>
                    <option value=White>Branco</option>
                    <option value=Black>Preto</option>
                    <option value=Green>Verde</option>
                    <option value=Red>Vermelho</option>
                </select>
            </div>
            <button type="submit" class="tiny alert right">Ver Coleção</button>
        </form>
    </div>

    <div class="small-10 large-4 columns panel right" >
        <div class="hide-for-small">
            <h3><small>Pesquisar por Nome de Card</small></h3>
            <div class="form-group">
                <form action="cards/" method="post">
                    <input type="text" name="card_name">
                    <button type="submit" class="tiny alert right">Pesquisar</button>
                </form>
            </div>
        <hr>
        </div>
        <h3><small>Pesquisar por Artista</small></h3>
        <div class="form-group">
            <form action="cards/" method="post">
                <input type="text" name="artist_name">
                <button type="submit" class="tiny alert right">Pesquisar</button>
            </form>
        </div>
    </div>

</div>